# Generated by Django 3.2.16 on 2022-12-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20221129_1252'),
        ('customer', '0009_user'),
        ('order', '0012_auto_20221129_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchid', models.CharField(max_length=50)),
                ('productid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='customer.user')),
            ],
        ),
    ]
