# Generated by Django 3.2.16 on 2022-12-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_purchase'),
        ('payment', '0006_auto_20221129_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('purchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='order.purchase')),
            ],
        ),
    ]
