# Generated by Django 3.2.16 on 2022-12-08 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_productalert_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='User')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
